# Generated by Django 6.1 on 2026-08-14 12:01

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=128)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro nao informar')], max_length=1)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('perfil', models.CharField(choices=[('DOADOR', 'Doador'), ('RECEPTOR', 'Receptor'), ('HEMOCENTRO', 'Hemocentro'), ('OBSERVADOR', 'Observador'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='data_cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', accounts.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id_consentimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_termo', models.CharField(choices=[('GERAL', 'Termos gerais e politica de privacidade'), ('TRIAGEM', 'Termo de triagem'), ('NOTIFICACOES', 'Termo de notificacoes')], max_length=20)),
                ('versao_termo', models.CharField(default='1.0', max_length=20)),
                ('aceito', models.BooleanField(default=False)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimento LGPD',
                'verbose_name_plural': 'consentimentos LGPD',
                'db_table': 'consentimentos_lgpd',
                'ordering': ['-data_aceite'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tipo_termo', 'versao_termo'), name='consentimento_unico_por_versao')],
            },
        ),
    ]
