# Generated by Django 6.1 on 2026-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='consentimentolgpd',
            name='tipo_termo',
            field=models.CharField(choices=[('GERAL', 'Termos gerais e politica de privacidade')], default='GERAL', max_length=20),
        ),
    ]
