# Generated by Django 6.1 on 2026-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_cidade_remove_usuario_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('DOADOR', 'Doador'), ('RECEPTOR', 'Receptor'), ('HEMOCENTRO', 'Hemocentro'), ('OBSERVADOR', 'Observador'), ('ADMINISTRADOR', 'Administrador')], default='OBSERVADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro'), ('N', 'Prefiro nao informar')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='consentimentolgpd',
            name='tipo_termo',
            field=models.CharField(choices=[('GERAL', 'Termos gerais e politica de privacidade'), ('TRIAGEM', 'Termo de triagem'), ('NOTIFICACOES', 'Termo de notificacoes')], default='GERAL', max_length=20),
        ),
    ]
