# Generated by Django 5.2.17 on 2026-08-21 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_cidade_usuario_cnpj_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcaoCritica',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('LOGIN_FALHO', 'Login falho'), ('LOGIN_SUSPEITO', 'Login suspeito'), ('ALTERACAO_PERMISSAO', 'Alteracao de permissao'), ('APROVACAO_HEMOCENTRO', 'Aprovacao de hemocentro'), ('ATUALIZACAO_ESTOQUE', 'Atualizacao de estoque'), ('MODERACAO', 'Moderacao'), ('ACESSO_DADOS_SENSIVEIS', 'Acesso a dados sensiveis'), ('CONFIRMACAO_DOACAO', 'Confirmacao de doacao')], max_length=40)),
                ('resultado', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha'), ('BLOQUEADO', 'Bloqueado')], default='SUCESSO', max_length=20)),
                ('alvo_tipo', models.CharField(blank=True, default='', max_length=80)),
                ('alvo_id', models.CharField(blank=True, default='', max_length=80)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acoes_criticas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auditoria de acao critica',
                'verbose_name_plural': 'auditorias de acoes criticas',
                'db_table': 'auditorias_acoes_criticas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acao', 'criado_em'], name='auditoria_acao_data_idx'), models.Index(fields=['usuario', 'criado_em'], name='auditoria_usuario_data_idx'), models.Index(fields=['ip', 'criado_em'], name='auditoria_ip_data_idx')],
            },
        ),
    ]
