# Generated by Django 5.2.17 on 2026-08-25 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditoriaacaocritica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status_validacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CORRECAO', 'Correcao necessaria')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='ValidacaoHemocentro',
            fields=[
                ('id_validacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CORRECAO', 'Correcao necessaria')], max_length=20)),
                ('parecer', models.TextField(blank=True, default='')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_hemocentro_realizadas', to=settings.AUTH_USER_MODEL)),
                ('hemocentro', models.ForeignKey(db_column='id_hemocentro', on_delete=django.db.models.deletion.CASCADE, related_name='validacoes_hemocentro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validacao de hemocentro',
                'verbose_name_plural': 'validacoes de hemocentros',
                'db_table': 'validacoes_hemocentro',
                'ordering': ['-data_analise'],
                'indexes': [models.Index(fields=['hemocentro', '-data_analise'], name='validacao_hemo_data_idx'), models.Index(fields=['status', 'data_analise'], name='validacao_hemo_status_idx')],
            },
        ),
    ]
