# Generated by Django 6.1 on 2026-08-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_status_validacao_validacaohemocentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id_triagem', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidade', models.CharField(choices=[('EXTENSA', 'Triagem extensa'), ('SIMPLIFICADA', 'Triagem simplificada')], default='EXTENSA', max_length=20)),
                ('regra_version', models.CharField(default='HEMOMINAS_2026_08', max_length=40)),
                ('resultado', models.CharField(choices=[('SEM_IMPEDIMENTO_IDENTIFICADO', 'Sem impedimento identificado'), ('INAPTIDAO_TEMPORARIA', 'Inaptidão temporária'), ('INAPTIDAO_DEFINITIVA', 'Inaptidão definitiva'), ('AVALIACAO_PRESENCIAL', 'Avaliação presencial'), ('DOCUMENTACAO_ESPECIAL', 'Documentação especial')], max_length=30)),
                ('mensagem_resultado', models.TextField()),
                ('data_liberacao', models.DateField(blank=True, null=True)),
                ('achados', models.JSONField(blank=True, default=list)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='triagens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'triagens',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaTriagem',
            fields=[
                ('id_resposta', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pergunta', models.CharField(max_length=20)),
                ('codigo_resposta', models.CharField(max_length=80)),
                ('resposta_label', models.CharField(max_length=255)),
                ('data_evento', models.DateField(blank=True, db_column='event_date', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule_version', models.CharField(default='HEMOMINAS_2026_08', max_length=40)),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('triagem', models.ForeignKey(db_column='id_triagem', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='accounts.triagem')),
            ],
            options={
                'db_table': 'respostas_triagem',
                'ordering': ['id_resposta'],
            },
        ),
        migrations.AddIndex(
            model_name='triagem',
            index=models.Index(fields=['usuario', '-iniciada_em'], name='triagem_usuario_data_idx'),
        ),
        migrations.AddIndex(
            model_name='triagem',
            index=models.Index(fields=['resultado', '-iniciada_em'], name='triagem_resultado_data_idx'),
        ),
        migrations.AddIndex(
            model_name='respostatriagem',
            index=models.Index(fields=['triagem', 'id_pergunta'], name='resposta_triagem_pergunta_idx'),
        ),
    ]
