# Generated by Django 5.2.17 on 2026-09-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_triagem_respostatriagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaacaocritica',
            name='acao',
            field=models.CharField(choices=[('LOGIN_FALHO', 'Login falho'), ('LOGIN_SUSPEITO', 'Login suspeito'), ('ALTERACAO_PERMISSAO', 'Alteracao de permissao'), ('APROVACAO_HEMOCENTRO', 'Aprovacao de hemocentro'), ('CADASTRO_ESTOQUE', 'Cadastro de estoque'), ('ATUALIZACAO_ESTOQUE', 'Atualizacao de estoque'), ('MODERACAO', 'Moderacao'), ('ACESSO_DADOS_SENSIVEIS', 'Acesso a dados sensiveis'), ('CONFIRMACAO_DOACAO', 'Confirmacao de doacao')], max_length=40),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_sanguineo', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=3)),
                ('quantidade_bolsas', models.PositiveIntegerField(default=0)),
                ('nivel_minimo', models.PositiveIntegerField()),
                ('nivel_critico', models.PositiveIntegerField()),
                ('status_calculado', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAIXO', 'Baixo'), ('ESTAVEL', 'Estável')], default='ESTAVEL', max_length=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('hemocentro', models.ForeignKey(db_column='id_hemocentro', limit_choices_to={'perfil': 'HEMOCENTRO'}, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoques',
                'db_table': 'estoques',
                'ordering': ['hemocentro__nome', 'tipo_sanguineo'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMovimentacao',
            fields=[
                ('id_mov', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('quantidade_anterior', models.PositiveIntegerField()),
                ('quantidade_movimentada', models.IntegerField()),
                ('quantidade_nova', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('estoque', models.ForeignKey(db_column='id_estoque', on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='accounts.estoque')),
                ('usuario_resp', models.ForeignKey(blank=True, db_column='id_usuario_resp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimentacao de estoque',
                'verbose_name_plural': 'movimentacoes de estoque',
                'db_table': 'movimentacoes_estoque',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['hemocentro', 'tipo_sanguineo'], name='estoque_hemo_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='estoque',
            index=models.Index(fields=['status_calculado'], name='estoque_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='estoque',
            constraint=models.UniqueConstraint(fields=('hemocentro', 'tipo_sanguineo'), name='estoque_unico_por_hemocentro_tipo'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['estoque', '-data_hora'], name='mov_estoque_data_idx'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentacao',
            index=models.Index(fields=['usuario_resp', '-data_hora'], name='mov_usuario_data_idx'),
        ),
    ]
