# Generated by Django 6.1 on 2026-09-04 12:10

import django.db.models.deletion
from django.db import migrations, models


def preencher_dados_da_triagem(apps, schema_editor):
    """Converte os registros da versão inicial para os campos novos."""

    Triagem = apps.get_model("accounts", "Triagem")
    RespostaTriagem = apps.get_model("accounts", "RespostaTriagem")

    # Uma triagem antiga com data final já estava concluída.
    Triagem.objects.filter(
        finalizada_em__isnull=False,
    ).update(status="CONCLUIDA")

    for resposta in RespostaTriagem.objects.all().iterator():
        # O formato estruturado mantém os dados legados disponíveis.
        resposta.valor = {
            "codigos": (
                [resposta.codigo_resposta]
                if resposta.codigo_resposta
                else []
            ),
            "data_evento": (
                resposta.data_evento.isoformat()
                if resposta.data_evento
                else None
            ),
            "detalhes": resposta.metadata.get("detalhes", ""),
            "metadata": resposta.metadata,
        }
        resposta.save(update_fields=["valor"])


def limpar_dados_da_triagem(apps, schema_editor):
    """Permite reverter a migration sem alterar os campos legados."""

    Triagem = apps.get_model("accounts", "Triagem")
    RespostaTriagem = apps.get_model("accounts", "RespostaTriagem")

    Triagem.objects.update(status="EM_ANDAMENTO")
    RespostaTriagem.objects.update(valor={})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_triagem_respostatriagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostatriagem',
            options={'ordering': ['id_resposta'], 'verbose_name': 'Resposta triagem', 'verbose_name_plural': 'Respostas triagem'},
        ),
        migrations.AlterModelOptions(
            name='triagem',
            options={'ordering': ['-iniciada_em'], 'verbose_name': 'Triagem', 'verbose_name_plural': 'Triagens'},
        ),
        migrations.AddField(
            model_name='respostatriagem',
            name='valor',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triagem',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triagem',
            name='fluxo_perguntas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='triagem',
            name='pergunta_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triagem',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='triagem',
            name='triagem_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_simplificadas', to='accounts.triagem'),
        ),
        migrations.RunPython(
            preencher_dados_da_triagem,
            limpar_dados_da_triagem,
        ),
        migrations.AlterField(
            model_name='triagem',
            name='mensagem_resultado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='resultado',
            field=models.CharField(blank=True, choices=[('SEM_IMPEDIMENTO_IDENTIFICADO', 'Sem impedimento identificado'), ('INAPTIDAO_TEMPORARIA', 'Inaptidão temporária'), ('INAPTIDAO_DEFINITIVA', 'Inaptidão definitiva'), ('AVALIACAO_PRESENCIAL', 'Avaliação presencial'), ('DOCUMENTACAO_ESPECIAL', 'Documentação especial')], default='', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='respostatriagem',
            constraint=models.UniqueConstraint(fields=('triagem', 'id_pergunta'), name='resposta_unica_por_pergunta'),
        ),
    ]
