# Generated by Django 5.2.17 on 2026-09-10 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_triagem_estoque_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='', max_length=3),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ESTOQUE_BAIXO', 'Estoque baixo'), ('ESTOQUE_CRITICO', 'Estoque crítico'), ('GERAL', 'Aviso geral')], default='GERAL', max_length=30)),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('url_destino', models.CharField(blank=True, default='', max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('estoque', models.ForeignKey(blank=True, db_column='id_estoque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='accounts.estoque')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificacao',
                'verbose_name_plural': 'notificacoes',
                'db_table': 'notificacoes',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['usuario', 'lida', '-criada_em'], name='notificacao_usuario_lida_idx'), models.Index(fields=['tipo', '-criada_em'], name='notificacao_tipo_data_idx')],
            },
        ),
    ]
