# Generated by Django 6.1 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_usuario_tipo_sanguineo_notificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoSangue",
            fields=[
                (
                    "id_pedido",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "para_quem",
                    models.CharField(
                        choices=[
                            ("MIM", "Para mim"),
                            ("OUTRA_PESSOA", "Para outra pessoa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_sanguineo",
                    models.CharField(
                        choices=[
                            ("O-", "O-"),
                            ("O+", "O+"),
                            ("A-", "A-"),
                            ("A+", "A+"),
                            ("B-", "B-"),
                            ("B+", "B+"),
                            ("AB-", "AB-"),
                            ("AB+", "AB+"),
                        ],
                        max_length=3,
                    ),
                ),
                ("cidade", models.CharField(max_length=100)),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("URGENTE", "Urgente"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nome_paciente",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                    ),
                ),
                ("descricao", models.TextField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("ATIVO", "Ativo"),
                            ("RECUSADO", "Recusado"),
                            ("ATENDIDO", "Atendido"),
                            ("EXPIRADO", "Expirado"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                (
                    "hemocentro",
                    models.ForeignKey(
                        db_column="id_hemocentro",
                        limit_choices_to={"perfil": "HEMOCENTRO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_de_destino",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        db_column="id_solicitante",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_publicados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pedido de sangue",
                "verbose_name_plural": "pedidos de sangue",
                "db_table": "pedidos_sangue",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["status", "-data_criacao"],
                        name="pedido_sangue_status_idx",
                    ),
                    models.Index(
                        fields=["cidade", "tipo_sanguineo"],
                        name="pedido_sangue_busca_idx",
                    ),
                ],
            },
        ),
    ]
