# Generated by Django 6.1 on 2026-10-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def alinhar_status_legados(apps, schema_editor):
    PedidoSangue = apps.get_model("accounts", "PedidoSangue")
    Triagem = apps.get_model("accounts", "Triagem")

    PedidoSangue.objects.filter(status="PENDENTE_VALIDACAO").update(
        status="ENVIADA"
    )
    PedidoSangue.objects.filter(status="ATIVO").update(status="PUBLICADA")
    PedidoSangue.objects.filter(status="SUSPEITO").update(status="EM_ANALISE")
    PedidoSangue.objects.filter(status="RECUSADO").update(status="RECUSADA")
    PedidoSangue.objects.filter(status="ENCERRADO").update(status="ENCERRADA")



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alinhar_pedidos_validacao'),
    ]

    operations = [
        migrations.RunPython(alinhar_status_legados, migrations.RunPython.noop),
        migrations.AddField(
            model_name='pedidosangue',
            name='contato',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedidosangue',
            name='duplicidade_suspeita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidosangue',
            name='informacoes_complementares',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedidosangue',
            name='nome_solicitante',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pedidosangue',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosangue',
            name='publicado_por',
            field=models.ForeignKey(blank=True, db_column='id_publicado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_publicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_sanguineo_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidosangue',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_column='id_solicitante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_sangue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidosangue',
            name='status',
            field=models.CharField(choices=[('ENVIADA', 'Enviada'), ('EM_ANALISE', 'Em análise'), ('PUBLICADA', 'Publicada'), ('CORRECAO_SOLICITADA', 'Correção solicitada'), ('RECUSADA', 'Recusada'), ('ENCERRADA', 'Encerrada')], default='ENVIADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='resultado',
            field=models.CharField(blank=True, choices=[('SEM_IMPEDIMENTO_IDENTIFICADO', 'Apto'), ('INAPTIDAO_TEMPORARIA', 'Inaptidão temporária'), ('INAPTIDAO_DEFINITIVA', 'Inaptidão definitiva'), ('AVALIACAO_PRESENCIAL', 'Avaliação presencial necessária'), ('DOCUMENTACAO_ESPECIAL', 'Documentação especial')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='validacaopedido',
            name='status_validacao',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('CORRECAO_SOLICITADA', 'Correção solicitada'), ('SUSPEITO', 'Suspeito'), ('RECUSADO', 'Recusado')], max_length=20),
        ),
    ]
