# Generated by Django 6.1 on 2026-10-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_pedidosangue_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suspensa',
            field=models.BooleanField(default=False),
        ),
    ]
