# Generated by Django 6.1 on 2026-10-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usuario_suspensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='accounts.pedidosangue'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aceita_notificacoes_pedidos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('ESTOQUE_BAIXO', 'Estoque baixo'), ('ESTOQUE_CRITICO', 'Estoque crítico'), ('PEDIDO_COMPATIVEL', 'Pedido compatível'), ('GERAL', 'Aviso geral')], default='GERAL', max_length=30),
        ),
    ]
