# Generated by Django 6.1 on 2026-10-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notificacao_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosangue',
            name='contato',
            field=models.EmailField(default='', max_length=120),
        ),
    ]
